repos:
   - repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.9.5
     hooks:
        - id: ruff  # Linter
          args: [--fix]  # Ensure fixes are applied
          files: ^lab0[1-9]
        - id: ruff-format  # Formatter
          files: ^lab0[1-9]
 
   # monitor code complexity
   - repo: https://github.com/rubik/xenon
     rev: v0.9.0
     hooks:
        - id: xenon
          files: ^lab01/lab/
          args: ['--max-absolute=B', '--max-modules=B', '--max-average=A']

   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v1.11.1
     hooks:
        - id: mypy # type checker
          files: ^lab01/homework/
          additional_dependencies: ['torch', 'transformers', 'joblib', 'clean-text', 'sentence_transformers', 'fastapi', 'pydantic']
          # args: [--explicit-package-bases]